#!/bin/bash

set -x

# format code:
uvx ruff check . --select I --fix
uvx ruff format .

# check code:
uvx ruff check
uvx mypy f2 tests

# run tests, unless disabled:
if [[ ! "$*" =~ --no-tests ]]; then
    uv run pytest
fi
